version: 2.1
orbs:
  windows: circleci/windows@2.4.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run: go test ./...
  test-windows:
    executor:
      name: windows/default
    steps:
      - checkout
      - attach_workspace:
          at: script
      - run: go test

workflows:
  version: 2
  test:
    jobs:
      - test
      - test-windows
