# Based on https://github.com/mvdan/github-actions-golang
on: [pull_request, workflow_dispatch]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test -race ./...
      
  gocritic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      - run: |
          go install github.com/go-critic/go-critic/cmd/gocritic@latest
          gocritic check .
